services:
  interpreter:
    container_name: interpreter
    # image: ghcr.io/enso-labs/interpreter:latest
    build: .
    restart: always
    ports:
      - "8888:8888"
      - "8001:8000"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - PYTHONPATH=/home/jovyan
    entrypoint: ["sh", "-c", "start-notebook.sh --NotebookApp.token=${JUPYTER_TOKEN} & uvicorn api:app --host 0.0.0.0 --port 8000"]
    volumes:
      - ./uploads:/tmp
      - ./notebooks:/home/jovyan/.ipynb_checkpoints